apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deepvol-worker-hpa
  namespace: deepvol
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deepvol-worker
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: External
    external:
      metric:
        name: kafka_consumergroup_lag
        selector:
          matchLabels:
            topic: option-quotes
            consumergroup: deepvol-calibrator-group
      target:
        type: AverageValue
        averageValue: "100" # Scale up when average lag per member exceeds 100 quotes
